version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    expose:
      - "3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    container_name: drupal9_db
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8600:80"
    links:
      - db
    volumes: 
      - ./composer.json:/opt/drupal/composer.json
      - ./settings.local.php:/opt/drupal/web/sites/default/settings.local.php
      - ./settings.php:/opt/drupal/web/sites/default/settings.php
      - ./config:/opt/drupal/config
    container_name: drupal9_web
